[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
over_under = "3qzsebktNn3EJCxjoCmmbHnu62x3ebGpKuyv5qBxLp8V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
sb = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sb.ts"
