[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
over_under = "4z3ZzM7rVH8D2mBuL81TuYBtAxMrWdDziKf8Z34tLxr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
