[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
over_under = "6qUeZY7njik5mb5Q3MCGkdyt8NSvyLtAxsDnErhVm6dV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/single_player.ts"
global = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init_global.ts"
round = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init_round.ts"
bet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/place_bet.ts"
multibet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/multiplayer.ts"
play = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/play_round.ts"
assess = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/assess_winners.ts"
payout = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/payout.ts"
close = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/close_round.ts"

